### ISSUE TITLE
PlatformIO (vscode) - basic examples not working with v1.0.5

### ISSUE THREAD

**Issue by mereshow** [arduino-libraries/SigFox#23]
Hi,
when using PlatformIO in vscode and the library is installed it installs v1.0.5 by default (latest) it fails to compile giving the error: 

```text
.pio/libdeps/mkrfox1200/Arduino SigFox for MKRFox1200/src/SigFox.cpp:34:10: fatal error: ArduinoLowPower.h: No such file or directory
```

If the version 1.0.4 is installed, it compiles without error (without changing anything else).

**Comment by per1234** [comment]
Hi @mereshow. This library has a dependency on the "**Arduino Low Power**" library. So you must make sure to also install that library:

https://registry.platformio.org/libraries/arduino-libraries/Arduino%20Low%20Power
